# Setup
title:               Tiberiu Teșileanu
tagline:             'a physicist working in neuroscience'
description:         > # the ">" symbol means to ignore newlines until indentation ends
  Neuroscience researcher with background in theoretical physics.
icon: /public/img/favicon.png # the emoji used as the favicon
use_custom_favicon: true # if this is true, you can set favicon path instead of using default emoji
baseurl:             ''
email:             ttesileanu@gmail.com

# About/contact
author:
  name:              Tiberiu Teșileanu
  url:               https://ttesileanu.github.io
  email:             ttesileanu@gmail.com

# Pagination
pagination:
  enabled: true

# Includes & excludes
include: ['_pages']
exclude:
  - old
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git

# Gems
plugins:
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-imagemagick

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:

  last_name: Tesileanu
  first_name: [Tiberiu, T.]

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  # Note: if you have latex math in your bibtex, the latex filter
  # preprocessing may conflict with MathJAX if the latter is enabled.
  # See https://github.com/alshedivat/al-folio/issues/357.
  bibtex_filters: [latex, smallcaps, superscript]

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  sort_by: year
  order: descending

  query: "@*"

  max_auth: 5


# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------

imagemagick:
  enabled: true
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - public/img/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
  output_formats:
    webp: "-quality 75%"


# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: ttesileanu # your GitHub user name
gitlab_username: # your GitLab user name
twitter_username: ttesileanu # your Twitter handle
linkedin_username: tiberiu-tesileanu-b471a5198 # your LinkedIn user name
scholar_userid: 8--imZAAAAAJ # your Google Scholar ID
orcid_id: # your ORCID ID
medium_username: # your Medium username
quora_username: Tiberiu-Tesileanu # your Quora username
publons_id: # your ID on Publons
research_gate_profile: # your profile on ResearchGate
blogger_url: # your blogger URL
work_url: # work page URL
keybase_username: # your keybase user name
wikidata_id: # your wikidata id
dblp_url: # your DBLP profile url
stackoverflow_id: 1352250 #your stackoverflow id

contact_note:


# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
mathjax:
  version: "3.2.0"
    

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics:    false  # enables google analytics
enable_panelbear_analytics: false  # enables panelbear analytics
enable_google_verification: false  # enables google site verification
enable_bing_verification:   false  # enables bing site verification
enable_masonry:             true   # enables automatic project cards arrangement
enable_math:                true   # enables math typesetting (uses MathJax)
enable_tooltips:            false  # enables automatic tooltip links generated
                                   # for each section titles on pages and posts
enable_darkmode:            true   # enables switching between light/dark modes
enable_navbar_social:       false  # enables displaying social links in the
                                   # navbar on the about page
enable_project_categories:  true   # enables categorization of projects into
                                   # multiple categories
enable_medium_zoom:         true   # enables image zoom feature (as on medium.com)
